// Core types used throughout the application

use serde::{Deserialize, Serialize};

/// View mode for switching between different bit visualizations
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum ViewMode {
    Bit,
    Byte,
    Ascii,
}

impl Default for ViewMode {
    fn default() -> Self {
        ViewMode::Bit
    }
}

// Note: OperationType and OperationCategory have been moved to src/operations/mod.rs
// They are now generated by the register_operations! macro for easier maintenance.
// Import them from crate::operations instead of crate::core.
